### ISSUE TITLE
为什么调用已经暴露的属性（exposed_FileMonitor）会报AttributeError的错误？

### ISSUE THREAD

**Issue by zhangboyi** [tomerfiliba-org/rpyc#411]
Describe the issue briefly here, including:

- 直接使用[该链接下案例](https://rpyc.readthedocs.io/en/latest/tutorial/tut5.html)的代码跑，为什么调用已经暴露的属性（exposed_FileMonitor）会报AttributeError: 'FileMonitorService' object has no attribute 'FileMonitor'
- 

```
stack trace / error log
/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/bin/python /Users/boyizhang/PycharmProjects/fastApi_demo/apscheld/async_client.py
Traceback (most recent call last):
  File "/Users/boyizhang/PycharmProjects/fastApi_demo/apscheld/async_client.py", line 13, in <module>
    mon = conn.root.FileMonitor('test.log',on_file_changed)
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/netref.py", line 166, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
AttributeError: 'FileMonitorService' object has no attribute 'FileMonitor'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/protocol.py", line 609, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/Users/boyizhang/PycharmProjects/virtualenv/fastApi_demo/lib/python3.8/site-packages/rpyc/core/protocol.py", line 537, in _access_attr
    return accessor(obj, name, *args)
AttributeError: 'FileMonitorService' object has no attribute 'FileMonitor'


Process finished with exit code 1

```

##### Environment

- rpyc version
- python version
- operating system

##### Minimal example

Server:

```python
class FileMonitorService(rpyc.SlaveService):
    class exposed_FileMonitor(object):
        def __init__(self,filename,callback,interval = 1):
            self.filename = filename
            self.interval = interval
            self.last_stat = None
            # create an async callback
            self.callback = rpyc.async_(callback)
            self.active = True
            self.thread = Thread(target=self.work)
            self.thread.start()
        def exposed_stop(self):
            self.active = False
            self.thread.join()

        def work(self):
            while self.active:
                stat = os.stat(self.filename)
                if self.last_stat is not None and self.last_stat != stat:
                    # notify the client of change
                    self.callback(self.last_stat,stat)

                self.last_stat =stat
                time.sleep(self.interval)
if __name__ == '__main__':
    from rpyc.utils.server import ThreadedServer
    print('启动服务器....')
    protocol_config = {'allow_public_attrs': True}
    ThreadedServer(FileMonitorService,port=18871,protocol_config=protocol_config).start()
    print('服务器已启动...')
```

Client:

```python
import rpyc
f = open('test.log','w')
conn = rpyc.connect('localhost',18871)
bgsrv = rpyc.BgServingThread(conn)
def on_file_changed(oldstat,newstat):
    print("file changed")
    print(f"old stat:{oldstat},new stat{newstat}")

mon = conn.root.FileMonitor('test.log',on_file_changed)
f.write("hello rpyc!")
f.flush()

print("----")

f.write("groop")
f.flush()
f.close()
mon.stop()
bgsrv.stop()
conn.close()
```

**Comment by comrumino** [comment]
It looks like you meant to inherit `rpyc.Service` instead of `class FileMonitorService(rpyc.Service)`. The `exposed_` prefix is for `rpyc.Service`. While `rpyc.SlaveService` does not require the `exposed_` prefix, it poses a major security risk in insecure networks.
