### ISSUE TITLE
rpyc_registry.py and rpyc_classic.py are broken due to change to set in Plumbum 'Set'

### ISSUE THREAD

**Issue by btjorgens** [tomerfiliba-org/rpyc#420]
Trying to activate the RPyC registry for TCP results in an error.
The issue is that Plumbum's Set operation now returns a lowercase value.
The Set default of 'UDP' is returned unchanged.
So if the user enters any value for mode, neither the if 'TCP' or 'UDP' clauses will catch and the server object will be used before being defined.

There are similar issues with rpyc_classic.py.

I can work around the issues with local copies of both scripts that match against the lower case values...

rpyc_registry.py --mode TCP
Traceback (most recent call last):
  File "/corp/sta/opt/Python-2.7/bin/rpyc_registry.py", line 42, in <module>
    RegistryServer.run()
  File "/corp/sta/opt/Python-2.7/lib/python2.7/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/corp/sta/opt/Python-2.7/bin/rpyc_registry.py", line 38, in main
    server.start()
UnboundLocalError: local variable 'server' referenced before assignment

##### Environment

- rpyc version - 4.1.5
- python version - 2.7
- operating system -  Oracle Linux 7.5

**Comment by comrumino** [comment]
Thanks for reporting. Any possibility of getting a unit test that reproduces the issue?
