### ISSUE TITLE
About the solution of raise EOFError(" Stream has been closed")

### ISSUE THREAD

**Issue by junhuanchen** [tomerfiliba-org/rpyc#421]
I also encountered this problem, this is my reference code, the case I used is as follows:

```python
            with rpyc.classic.redirected_stdio(self.remote):
                try:
                    self.remote.execute(code)
                except KeyboardInterrupt as e:
                    self.remote.execute("raise KeyboardInterrupt")
                    self.log.error(self.remote)
                except Exception as e:
                    self.log.error(e)
                    self.do_connect()
```

At first I found that the remote socket caused the host to take the initiative to self.remote.modules.builtins.exit(1) to cause the connection between the two parties to fail, and self.remote.execute("raise KeyboardInterrupt") would cause the remote core/stream.py to fail. , But note that at this time, the host can still connect to the remote. This seems a bit strange, which means that the host can still work, but the remote cannot send to (return) host.

It will appear the following remote Traceback.

```python
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 604, in _handle_inspect
    return conn.sync_request(consts.HANDLE_INSPECT, id_pack)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 493, in async_request
    self._async_request(handler, args, res)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 475, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 259, in _send
    self._channel.send(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/channel.py", line 78, in send
    self.stream.write(header + data + self.FLUSHER)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/stream.py", line 267, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/stream.py", line 94, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```

Note that this is the remote Traceback, obviously the remote steam.send at this time is invalid.

Therefore, after judgment, I rewritten the scope of with, and removed the interrupt operation area from the scope of rpyc (such as after the end of _async).

```python
        try:
            try:
                with rpyc.classic.redirected_stdio(self.remote):
                    self.remote.execute(code)
            except KeyboardInterrupt as e:
                self.remote.execute("raise KeyboardInterrupt")
        except Exception as e:
            self.log.error(e)
            self.do_connect()
```

However, although this change can work, after multiple interruptions, there will be a Segmentation fault (core dumped) problem, I think it may have other problems, you can pay attention to it again.

The most effective method is self.remote.modules.builtins.exit(1) # not sys, but this will cause the connection to be closed safely this time, but the closing of the connection is not very friendly to the user during use.

Finally, please remember to add a guard to the slave program, the analysis process is for reference.

**Comment by junhuanchen** [comment]
Segmentation fault.

```bash
root@linux-lab:/labs/rpyc/bin# python3  -X faulthandler /labs/rpyc/bin/rpycs.py
Fatal Python error: Segmentation fault

Current thread 0x00007f208d386700 (most recent call first):
  File "<string>", line 4 in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/service.py", line 152 in execute
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 593 in _handle_call
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 320 in _dispatch_request
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 358 in _dispatch
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 392 in serve
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 408 in serve_all
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/utils/server.py", line 212 in _handle_connection
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/utils/server.py", line 206 in _serve_client
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/utils/server.py", line 184 in _authenticate_and_serve_client
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f208e1f5740 (most recent call first):
  File "/usr/lib/python3.8/socket.py", line 292 in accept
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/utils/server.py", line 142 in accept
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rpyc/utils/server.py", line 266 in start
  File "/labs/rpyc/bin/rpycs.py", line 7 in <module>
Segmentation fault (core dumped)
root@linux-lab:/labs/rpyc/bin# 

```

**Comment by junhuanchen** [comment]
I have completed the remote call code rpyc ikernel that I need. The reference code is as follows:

I think with rpyc.classic.redirected_stdio(self.remote): there is a deadlock, which may happen when the thread is killed.

So I redirected to the remote from the beginning.

The reference code is as follows:

https://github.com/junhuanchen/rpyc_ikernel/blob/f5cab7b5768ef4ad75918f1d02af02daf05bc8e6/examples/rpyc_call.py#L105-L146

**Comment by comrumino** [comment]
After spending a bit of time on this, this is intended behavior. Of course, I'm willing to revisit in the future.

By choosing to throw `ctypes.pythonapi.PyThreadState_SetAsyncExc`, there seems to be a chance that it segfaults inside of print. The other major design issue here is redirecting stdio and trying to support CTRL+C which creates a synchronization nightmare since the server is threaded. Moreover, if there is more than one client you have unexpected behavior.

I would more carefully consider what you are trying to achieve here. Consider using the new-style RPyC services and be more careful with shared state between connections.
