### ISSUE TITLE
Issue with launching threads on remote and waiting on future on local

### ISSUE THREAD

**Issue by ripare** [tomerfiliba-org/rpyc#436]
Hello, 

We're trying to launch a bunch of threads on the server and wait on their result on a client using Python's future API. Here's a minimal example that will show the exact problem we are encountering.

```
#a_simple_module.py
import concurrent.futures
from time import sleep
pool = concurrent.futures.ThreadPoolExecutor(max_workers=10)
def a_simple_function(a_number):
    print(f"Running with number {a_number}")
    sleep(1)
```
```
#just_a_server.py
from rpyc import ThreadedServer, SlaveService
t = ThreadedServer(SlaveService, port=12345).start()
```
```
#a_simple_client
import rpyc
from concurrent.futures import wait
c = rpyc.classic.connect("localhost", port=12345)
c.execute("import a_simple_module")
wait([c.modules.a_simple_module.pool.submit(c.modules.a_simple_module.a_simple_function, i) for i in range(10)])
```

Here's the exception text.
```
Exception in worker
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "C:\Program Files\Python37\lib\concurrent\futures\thread.py", line 63, in run
    self.future.set_result(result)
  File "C:\Program Files\Python37\lib\concurrent\futures\_base.py", line 522, in set_result
    waiter.add_result(self)
  File "C:\Users\rpare\AppData\Roaming\Python\Python37\site-packages\rpyc\core\netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "C:\Users\rpare\AppData\Roaming\Python\Python37\site-packages\rpyc\core\netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\rpare\AppData\Roaming\Python\Python37\site-packages\rpyc\core\protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\rpare\AppData\Roaming\Python\Python37\site-packages\rpyc\core\async_.py", line 100, in value
    self.wait()
  File "C:\Users\rpare\AppData\Roaming\Python\Python37\site-packages\rpyc\core\async_.py", line 49, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired
```

There is however a way to make it work.

```
import rpyc
from concurrent.futures import wait
c = rpyc.classic.connect("localhost", port=12345)
c.execute("import a_simple_module")
futures = [c.modules.a_simple_module.pool.submit(c.modules.a_simple_module.a_simple_function, i) for i in range(10)]
results = [f.result() for f in futures]
```

This version of the file works as expected and accomplishes the same goal.

Thank you for your time.

- rpyc version 5.0.1
- python version 3.7.5
- Windows 10

**Comment by comrumino** [comment]
In your first implementation you are using a local wait, for a simple function being submitted on remote. It may also be worth while to look into configuring `"sync_request_timeout": None` so that results would not timeout. If you find an underlying bug, feel free to reopen!
