### ISSUE TITLE
sporadic deadlock in syncreq

### ISSUE THREAD

**Issue by walterschneider** [tomerfiliba-org/rpyc#449]
We are sporadically having an issue stucking in syncreq from variaus calls.
However when the timeout expires, execution continues normaly without any exception.

It can be reproduced when:
- running server and client at the same CPU (using taskset command)
- creating some background-serving-threads at the client
- adding a delay in the _dispatch function
  (formerly added some logging here, but a delay with 0 seconds triggered the issue as well)

```
$ taskset -c 0 python3 client.py 
^CTraceback (most recent call last):
  File "client.py", line 15, in <module>
    conn.execute("import time")
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 474, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/async_.py", line 100, in value
    self.wait()
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/async_.py", line 47, in wait
    self._conn.serve(self._ttl)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/channel.py", line 47, in poll
    return self.stream.poll(timeout)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/stream.py", line 47, in poll
    rl = p.poll(timeout.timeleft())
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/lib/compat.py", line 122, in poll
    events = self._poll.poll(timeout)
KeyboardInterrupt
```

##### Environment

- rpyc 5.0.1 (same with 4.0.2)
- python 3.6
- operating Ubuntu 18.04 (bionic)

##### Minimal example

Patch

```diff
diff --git a/rpyc/core/protocol.py b/rpyc/core/protocol.py
index baef019..977316b 100644
--- a/rpyc/core/protocol.py
+++ b/rpyc/core/protocol.py
@@ -358,6 +358,7 @@ class Connection(object):
 
     def _dispatch(self, data):  # serving---dispatch?
         msg, seq, args = brine.load(data)
+        time.sleep(0.0)
         if msg == consts.MSG_REQUEST:
             self._dispatch_request(seq, args)
         elif msg == consts.MSG_REPLY:
```

Server:

```bash
taskset -c 0 rpyc_classic.py
```

Client:

```python
import time
import rpyc

conn = rpyc.classic.connect("localhost")

bg_threads = []

for i in range(3):
    bg_threads.append(rpyc.BgServingThread(conn))

if __name__ == "__main__":
    t0 = time.time()
    conn.execute("import time")
    print(time.time() - t0)
```

Run Client:

```bash
taskset -c 0 python3 client.py
```

**Comment by walterschneider** [comment]
My be same as / related to https://github.com/tomerfiliba-org/rpyc/issues/354

**Comment by comrumino** [comment]
You're a saint for providing a minimal example. I'll see what I can find

**Comment by comrumino** [comment]
I can reproduce the issue on 3.6, 3.7, 3.8, and 3
[https://stro.nz/public/rpyc-issue-449.pcap](https://stro.nz/public/rpyc-issue-449.pcap)
I'll have to dig a bit further.

**Comment by wumb0** [comment]
This issue needs to be reopened, as #455 was undone by #463
