### ISSUE TITLE
Dict is not callable?

### ISSUE THREAD

**Issue by Ixiodor** [tomerfiliba-org/rpyc#456]
Describe the issue briefly here, including:
I'm going to call a function on server that gives back a dict and there are some problems:
- I can print the dict
- I can't inspect the dict
- Passing it to a Django context ( I want render dict results to a template) I get: "TypeError: 'dict' object is not callable"
- Doing a copy.copy of dict before passing to Django as context, makes the dict usable.

```
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: 'dict' object is not callable
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/ubuntu/python-dev/manager_bot/venv/lib/python3.9/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
```

##### Environment

- rpyc version =5.0.1
- python version 3.9
- operating system Ubuntu

##### Minimal example
An example would be really large cause Django involved

**Comment by Ixiodor** [comment]
Debugging seems that this check:
`if callable(current):`
return True for your sended dict...

**Comment by Jongy** [comment]
I can confirm this happens on RPyC 5.0.1, I tried `callable(x.__dict__)` (where `x` is some netref object) and it returns `True`.

**Comment by Jongy** [comment]
I thought about it - it makes total sense: netrefs need to implement `__call__`, so that it can be forwarded over the connection. `callable()` merely checks for its existence (without calling it). Actually calling it forwards it over the connection and the remote side raises this `TypeError`.

The solution should probably be to use `inspect.isfunction` et al, which boil down to `isinstance()` calls which are intercepted and fixed by rpyc (unlike `callable()`).

**Comment by Ixiodor** [comment]
Maybe I didn't get the solution, but I can't fix Django.
Are you talking about fixing RPyC behaviour?

**Comment by Jongy** [comment]
> Maybe I didn't get the solution, but I can't fix Django.
> Are you talking about fixing RPyC behaviour?

Talking about Django. It can't be solved cleanly in RPyC. (it can be solved by patching the builtin `callable`, but patching builtins is not something RPyC does at the moment)

**Comment by Ixiodor** [comment]
There is a way to download object? I saw now that can't even update a netrefs dict.

**Comment by Jongy** [comment]
Using `copy.copy` is a legit solution, to un-netref dicts, yeah. (you might need `copy.deepcopy`, if the dict is nested)

**Comment by comrumino** [comment]
IMO, the confusion stems from "what is predictable behavior" for built-in functionality implemented in C (e.g. `callable`). The [C implementation of `callable`](https://github.com/python/cpython/blob/b83861f0265e07207a6ae2c49c40fa8f447893f2/Python/bltinmodule.c#L459-L476) is a low-level function operating on a high-level object. 

Suppose RPyC modified the global namespace so that `callable` was a netref. Modification of the global namespace for built-in functions will have more adverse effects and result in unpredictable behavior. By "patching" the built-in function as @Ixiodor did, the built-in shadowed the name so that resolution is your desired function.

I'd be open to a contribution of patching built-in functions. Here are my thoughts about different approaches
1. Add a function that will patch a specific scope
2. The function used to "patch" may want to use the local built-in for local objects and the remote built-in for netrefs
3. How would this function work for scripts that are using three or more address spaces (e.g. local, remote computer 1, and remote computer 2)?

@Jongy Thanks for jumping in.

**Comment by comrumino** [comment]
From looking at #459 , I thought that another approach would be
- a utility function that synchronizes the name bindings of a remote address space to the module it was executed within
- said function would shadow built-ins and allow the module to be written in a way that transparently executes in the remote address space
