### ISSUE TITLE
Can not use Netrefs from other thread

### ISSUE THREAD

**Issue by Jlo6CTEP** [tomerfiliba-org/rpyc#477]
I'm trying to befriend rpyc and asyncio, so that I have a secondary thread that runs rpyc server and handles connections and Netrefs, and the main thread with asyncio event loop that handles the core logic of my application. However, when I save an object in the rpyc thread, I can not use it from the event loop thread (or any other thread except the server thread)

### Minimal example
Client
```python

import asyncio
import rpyc


class ClientServiceLol(rpyc.Service):
    def exposed_foo(self, item):
        print('I got', item)


async def keep_alive():
    while True:
        await asyncio.sleep(1)


if __name__ == '__main__':
    s = ClientServiceLol()
    con = rpyc.connect('localhost', 18861, s, config={'allow_pickle': True})
    con.root.foo(s)
    asyncio.run(keep_alive())
```

and Server

```python
import asyncio
import threading
from threading import Thread

import rpyc
from rpyc.utils.server import ThreadedServer


class ServerServiceLol(rpyc.Service):
    def __init__(self):
        super().__init__()
        self.bar = None

    def on_connect(self, conn):
        print('1', threading.current_thread())
        self.bar = conn.root
        self.bar.foo(2)

    def exposed_foo(self, bar):
        print('Got a call from client')
        print('2', threading.current_thread())
        self.bar.foo(3)

    async def main(self):
        while True:
            await asyncio.sleep(0.1)
            if self.bar:
                print('Processing in event loop')
                print('3', threading.current_thread())
                self.bar.foo(5)

                print('Done here')


# Because I'm on Windows and python 3.7
async def wakeup():
    while True:
        await asyncio.sleep(1)


async def setup(service):
    await asyncio.gather(service.main(), wakeup())


if __name__ == "__main__":
    service = ServerServiceLol()
    server = ThreadedServer(service, port=18861,
                            protocol_config={'allow_pickle': True})
    server_thread = Thread(target=server.start)
    server_thread.start()
    asyncio.run(setup(service))
```
### Expected vs actual behavior 
* Expected behavior: I can invoke services on a Netref from the event loop thread, so the client's output should be
```
I got 2
I got 3
I got 5
```
* Actual behavior: An invocation hangs for 30 sec (default timeout) and then timeouts like that.
```
Traceback (most recent call last):
  File "C:/Users/ysuho/Documents/VimeIntel/test_server.py", line 53, in <module>
    asyncio.run(setup(service))
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:/Users/ysuho/Documents/VimeIntel/test_server.py", line 44, in setup
    await asyncio.gather(service.main(), wakeup())
  File "C:/Users/ysuho/Documents/VimeIntel/test_server.py", line 32, in main
    self.bar.foo(5)
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\async_.py", line 100, in value
    self.wait()
  File "C:\Users\ysuho\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\async_.py", line 49, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired
```
Client only receives 
```
I got 2
I got 3
```

### Environment
Windows 11 21H2, build 22000.493
Python 3.7.6
rpyc 5.0.1

**Comment by gschaffner** [comment]
Hi! This is because your client is not running a server to listen for requests for it to execute the callback. This will work if you add `callback_server = rpyc.BgServingThread(con)` to your client. Alternatively, you can run a blocking callback server on the client with `con.serve_all()`. Alternatively, if your client is async, you can run an asyncio callback server on the client with e.g.

```python
async def async_serve(con, sleep_interval=rpyc.BgServingThread.SLEEP_INTERVAL):
    while True:
        con.poll_all()
        await asyncio.sleep(sleep_interval)


if __name__ == "__main__":
    ...
    asyncio.run(async_serve(con))
```

See also #437.

Note that when using `BgServingThread` or `async_serve` with default `sleep_interval`, the frequency of callback prints is lower than when using `con.serve_all`. This is because `BgServingThread.SLEEP_INTERVAL = 0.1` is too slow for how quickly you are trying to make callbacks. I think the following is happening: it takes (up to) 0.1 s for the client to process your request to get a netref to `self.bar.foo`, followed by 0.1 s for the client to process your call to `self.bar.foo`. Your `main()` thread then sleeps for 0.1 s, making the actual time between `self.bar.foo()` calls in `main()` 0.3 s rather than 0.1 s.

To actually get callbacks every 0.1 s, you can decrease the sleep interval for `async_serve`. `BgServingThread` doesn't currently allow customizing its sleep interval.

@comrumino Do you know why replacing `self.bar.foo(5)` with `rpyc.async_(self.bar.foo)(5)` doesn't cause the time between callbacks to decrease from 0.3 s to 0.2 s? It stays at 0.3 s, and in particular the line `rpyc.async_(self.bar.foo)(5)` blocks for 0.2 s just like `self.bar.foo(5)`.

Additionally, do you know why `foo = self.bar.foo; foo(5)` takes 0.1 s longer than `self.bar.foo(5)`? In particular, `foo = self.bar.foo` takes 0.2 s; foo(5) takes the expected 0.1 s. Does assignment of a netref cause an additional network request? My guess was that this difference could be due to a `HANDLE_DEL`, but after some testing this doesn't appear to be the case.

**Comment by comrumino** [comment]
Off the top of my head, I would suspect foo assignment spends most of the time checking attribute access and initial creation of foo. Future name binding to self.bar.foo I would suspect take little to no time as it should be cached. The time foo(5) takes is strongly dependent on `sleep_interval` value (e.g., ` callback_server = rpyc.BgServingThread(con, sleep_interval=1)`)
Constructing the netref probably

There were possibly some silent errors in the code from asyncio. To add on 
**server**
```
import asyncio
import threading
from threading import Thread

import rpyc
from rpyc.utils.server import ThreadedServer
logger = rpyc.setup_logger()
rpyc.core.protocol.DEFAULT_CONFIG['logger'] = logger
rpyc.core.protocol.DEFAULT_CONFIG['sync_request_timeout'] = 10


class ServerServiceLol(rpyc.Service):
    def __init__(self):
        super().__init__()
        self.bar = None

    def on_connect(self, conn):
        logger.info(threading.current_thread())
        self.bar = conn
        self.bar.root.foo(2)

    def on_disconnect(self, conn):
        self.bar = None

    def exposed_foo(self, bar):
        logger.info('Got a call from client')
        self.bar.root.foo(3)

    async def main(self):
        while True:
            await asyncio.sleep(0.1)
            try:
                if self.bar and not self.bar.closed:
                    logger.info('Processing in event loop')
                    self.bar.root.foo(5)

                    logger.info('Done here')
                else:
                    self.bar = None
            except EOFError:
                self.bar = None


# Because I'm on Windows and python 3.7
async def wakeup():
    while True:
        await asyncio.sleep(1)


async def setup(service):
    await asyncio.gather(service.main(), wakeup())


if __name__ == "__main__":
    service = ServerServiceLol()
    server = ThreadedServer(service, port=18861,
                            protocol_config={'allow_pickle': True})
    server_thread = Thread(target=server.start)
    server_thread.start()
    asyncio.run(setup(service))
```
**client**
```
import asyncio
import rpyc
logger = rpyc.setup_logger()
rpyc.core.protocol.DEFAULT_CONFIG['logger']=logger
rpyc.core.protocol.DEFAULT_CONFIG['sync_request_timeout'] = 10


class ClientServiceLol(rpyc.Service):
    def exposed_foo(self, item):
        logger.info(f'I got {item}')


async def keep_alive():
    while True:
        await asyncio.sleep(1)


if __name__ == '__main__':
    s = ClientServiceLol()
    con = rpyc.connect('localhost', 18861, s, config={'allow_pickle': True})
    callback_server = rpyc.BgServingThread(con)
    con.root.foo(s)
    asyncio.run(keep_alive())
```
