### ISSUE TITLE
Porting from 3.4.4 to 5.1.0 issue, missing `self` argument on exposed methods.

### ISSUE THREAD

**Issue by gnif** [tomerfiliba-org/rpyc#481]
Describe the issue briefly here, including:

I am porting some scripts to use rpyc 5.1.0 however something seems to be wrong in our usage, calling even simple exposed methods with no arguments results in the following:

```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
TypeError: exposed_ping() missing 1 required positional argument: 'self'
```

##### Environment

- rpyc version: 5.1.0
- python version: 3.7
- operating system: Debian 10

##### Minimal example

I have tried to provide as much here as I can but due to security reasons I can not expose the socket authentication details we are performing prior. Please note however that we are handing rpyc a standard UNIX socket that has been created via `socket.socket` after we are done with our authentication mechanism. This was all working fine prior to the upgrade to 5.1.0 indicating that the data stream has not been corrupted or left in a bad state before handing it to rpyc.

Server:

```python
class MyService(rpyc.Service):

  def exposed_ping(self):
    return "pong"
 ```

```python
# sock has been provided by our authentication mechanism

config = dict(
  credentials = None,
  endpoints   = (sock.getsockname(), sock.getpeername()),
  logger      = self.logger
)
conn = Connection(
  MyService,
  Channel(SocketStream(sock), compress=False),
  config = config
)
conn.serve_all()
```

Client:

```python
rpc = rpyc.utils.factory.connect_stream(SocketStream(sock))
rpc.root.ping()
```

**Comment by gnif** [comment]
Just verified communications are indeed working as `rpc.ping()` does not throw an exception.

**Comment by gnif** [comment]
I found the issue, it seems the service `MyService` now needs to be constructed as an object, ie:
```python
conn = Connection(
  MyService(),
  Channel(SocketStream(sock), compress=False),
  config = config
)
```
