### ISSUE TITLE
Timeout when calling rpyc.utils.classic.obtain on server

### ISSUE THREAD

**Issue by RogerNi** [tomerfiliba-org/rpyc#501]
Describe the issue briefly here, including:

- expected result versus actual result
  - Expected to obtain remote object
  - Actual result: timeout on server side
- involved/problematic methods, e.g. `__call__`
  - Call `rpyc.utils.classic.obtain` on server to retrieve large objects from client side

```
stack trace / error log

Traceback (most recent call last):
  .......
  File "......", line 41, in query
    out = conn.root.test(self._least_len,list_list_codes)
  File "/usr/local/lib/python3.8/dist-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/local/lib/python3.8/dist-packages/rpyc/core/protocol.py", line 474, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/local/lib/python3.8/dist-packages/rpyc/core/async_.py", line 103, in value
    raise self._obj
TimeoutError: [Errno None] None: None -> None

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "cov_service.py", line 18, in exposed_test
    inputs = rpyc.utils.classic.obtain(inputs)
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/utils/classic.py", line 293, in obtain
    return pickle.loads(pickle.dumps(proxy))
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/netref.py", line 206, in __reduce_ex__
    return pickle.loads, (syncreq(self, consts.HANDLE_PICKLE, proto),)
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/protocol.py", line 474, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/async_.py", line 101, in value
    self.wait()
  File "/home/rni/anaconda3/envs/tf2-9andcc6-1/lib/python3.9/site-packages/rpyc/core/async_.py", line 50, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired
```

##### Environment

- rpyc version `rpyc==5.1.0`
- python version `Python==3.9.12`
- operating system: Ubuntu 20.04.4 LTS (Focal Fossa)

##### Minimal example

Server:

```python
import rpyc
from rpyc.utils.server import OneShotServer


class HelloService(rpyc.Service):
    def exposed_concat(self, remote_str):
        inputs = rpyc.utils.classic.obtain(remote_str) # this fails


if __name__ == "__main__":
    rpyc.lib.setup_logger()
    server = OneShotServer(HelloService, port=12345)
    server.start()
```

Client:

```python
import rpyc


if __name__ == "__main__":
    c = rpyc.connect("localhost", 12345, config={'sync_request_timeout': None}) # not useful even set timeout to none here
    print(c.root.concat(SOME_REALLY_LONG_DATA))
```

**Comment by comrumino** [comment]
The timeout you are seeing is on the server side. You have configured the timeout on the client side for results. When you invoke obtain on the server side, the result you are waiting for will timeout after 30 seconds b/c that is the default. More likely than not you wish to use deliver. That way, the time taken to pickle is part of the result timeout.

Some other settings to considered when you are sending a lot of data are `rpyc.core.channel.Channel.COMPRESSION_LEVEL` and `rpyc.core.stream.SocketStream.MAX_IO_CHUNK`.
