### ISSUE TITLE
hangs when invoke functions on multiple clients

### ISSUE THREAD

**Issue by zingdle** [tomerfiliba-org/rpyc#528]
##### Problems

I'm using rpyc to to help multiple clients call each other's functions remotely. In my case, there's one server holding all remote functions, and clients can connect the server to register and invoke other clients' remote functions.

##### Minimal example

```python
# Server

import rpyc

class MyService(rpyc.Service):
    func_dict = {}

    def exposed_set_func(self, name, f):
        self.func_dict[name] = f

    def exposed_call_func(self, name):
        return self.func_dict[name]()

    def exposed_get_func_dict(self):
        return self.func_dict
    

if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(MyService, port=18861)
    t.start()
```

When there's only Client A, it worked pretty well.

```python
# Client A
import rpyc
c = rpyc.connect("localhost", port=18861)

def a():
	return 123

c.root.set_func("a", a)
c.root.get_func_dict()              # {'foo': <function foo at 0x7f0f08fa4160>}
c.root.call_func("a")		               # 123
```

But when another client trying to get `func_dict` it hangs:

```python
# Client B

import rpyc
c = rpyc.connect("localhost", port=18861)

c.root.get_func_dict()	                  # hangs here
```

This function returns when arbituraty function is invoked on Client A (e.g. `get_func_dict`).

the backtrace here indicates that it stuck on `poll`:

```
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 196, in __repr__
    return syncreq(self, consts.HANDLE_REPR)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 718, in sync_request
    return _async_res.value
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/async_.py", line 106, in value
    self.wait()
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/async_.py", line 51, in wait
    self._conn.serve(self._ttl)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 434, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/channel.py", line 47, in poll
    return self.stream.poll(timeout)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/stream.py", line 48, in poll
    rl = p.poll(timeout.timeleft())
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/lib/compat.py", line 124, in poll
    events = self._poll.poll(timeout)
KeyboardInterrupt
```

When I'm closing Client A, and `get_func_dict` again on Client B, the stream is broken:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 196, in __repr__
    return syncreq(self, consts.HANDLE_REPR)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 474, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/async_.py", line 103, in value
    raise self._obj
_get_exception_class.<locals>.Derived: stream has been closed

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 577, in _handle_repr
    return repr(obj)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 196, in __repr__
    return syncreq(self, consts.HANDLE_REPR)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 474, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 498, in async_request
    self._async_request(handler, args, res)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 480, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/protocol.py", line 263, in _send
    self._channel.send(data)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/channel.py", line 78, in send
    self.stream.write(header + data + self.FLUSHER)
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/stream.py", line 268, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/home/user/anaconda3/envs/demo/lib/python3.9/site-packages/rpyc/core/stream.py", line 95, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```

##### Environment

- rpyc version: 5.3.0, 5.1.0
- python version: 3.9.16
- operating system: Ubuntu 20.04

**Comment by comrumino** [comment]
Is this still an issue in the latest release?

**Comment by zingdle** [comment]
yes, it's still no working in 5.3.1

**Comment by comrumino** [comment]
Solution: client-a needs a background thread to serve. 
Why: Passing function a to the serve creates a netref/proxy-object. While client-b interacts with the server, the server calls the function and executes it within client-a. I rewrote the server and clients to illustrate where things are executing and the import/export functions. 
`server.py`
```
import rpyc
import inspect
from rpyc.utils.teleportation import import_function
rpyc.core.DEFAULT_CONFIG['logger'] = rpyc.lib.setup_logger()

class MyService(rpyc.Service):
    func_dict = {}

    def exposed_set_func(self, name, f):
        self.func_dict[name] = f

    def exposed_import_func(self, name, f):
        self.func_dict[name] = import_function(f)

    def exposed_call_func(self, name):
        return self.func_dict[name]()

    def exposed_get_func_dict(self):
        return self.func_dict
    

if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(MyService, hostname='localhost', port=18861)
    t.start()
```

`client-a.py`
```
# Client A
import rpyc
from rpyc.utils.teleportation import export_function
import time
import inspect
c = rpyc.connect("localhost", port=18861)
bg_server = rpyc.BgServingThread(c)

def a():
    parent_frame = inspect.getouterframes( inspect.currentframe() )[1]
    print(f'a was called by {parent_frame}')
    return 123

c.root.set_func("client_side_a", a)
c.root.get_func_dict()              # {'foo': <function foo at 0x7f0f08fa4160>}
c.root.call_func("client_side_a")		               # 123
c.root.import_func('server_side_a', export_function(a))
try:
    while True:
        time.sleep(5)
except KeyboardInterrupt:
    bg_server.stop()
    c.close()
```
`client-b.py`
```
# Client B

import rpyc
rpyc.core.DEFAULT_CONFIG['logger'] = rpyc.lib.setup_logger()
c = rpyc.connect("localhost", port=18861)
c.root.call_func('client_side_a')
func_dict_netref = c.root.get_func_dict()	                  # hangs here, when client-a doesn't have a background thread to serve client-b
func_dict_netref['client_side_a']()
func_dict_netref['server_side_a']()
```

RPyC usability is not the best when it comes to serving responses. The bind threading work will allow for some usability improvements around serving. I hope this helps.
