### ISSUE TITLE
6.0.0: pytest fails in 6 units

### ISSUE THREAD

**Issue by kloczek** [tomerfiliba-org/rpyc#556]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-rpyc-6.0.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-rpyc-6.0.0-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network' --ignore tests/test_affinity.py --ignore tests/test_service_pickle.py
============================= test session starts ==============================
platform linux -- Python 3.10.14, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0
configfile: pyproject.toml
collected 93 items

tests/test_async.py .....                                                [  5%]
tests/test_attr_access.py .........                                      [ 15%]
tests/test_attributes.py F                                               [ 16%]
tests/test_brine.py .                                                    [ 17%]
tests/test_classic.py ...F.                                              [ 22%]
tests/test_context_managers.py ..                                        [ 24%]
tests/test_custom_service.py .......                                     [ 32%]
tests/test_dataclass.py .                                                [ 33%]
tests/test_deploy.py ...s                                                [ 37%]
tests/test_gdb.py F                                                      [ 38%]
tests/test_get_id_pack.py ....                                           [ 43%]
tests/test_gevent_server.py sss                                          [ 46%]
tests/test_ipv6.py s                                                     [ 47%]
tests/test_magic.py FF                                                   [ 49%]
tests/test_netref_hierachy.py ......F....                                [ 61%]
tests/test_oneshot_server.py .                                           [ 62%]
tests/test_race.py .                                                     [ 63%]
tests/test_refcount.py .                                                 [ 64%]
tests/test_registry.py ......                                            [ 70%]
tests/test_remote_exception.py ..                                        [ 73%]
tests/test_remoting.py s.s.s                                             [ 78%]
tests/test_rpyc_over_rpyc.py ...                                         [ 81%]
tests/test_ssh.py ..                                                     [ 83%]
tests/test_ssl.py .                                                      [ 84%]
tests/test_teleportation.py ......                                       [ 91%]
tests/test_threaded_server.py ...                                        [ 94%]
tests/test_threads.py .                                                  [ 95%]
tests/test_urllib3.py s                                                  [ 96%]
tests/test_win32pipes.py sss                                             [100%]

=================================== FAILURES ===================================
________________________ TestAttributes.test_properties ________________________

self = <tests.test_attributes.TestAttributes testMethod=test_properties>

    def test_properties(self):
>       p = self.conn.modules["test_attributes"].Properties()

tests/test_attributes.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rpyc/core/service.py:132: in __getitem__
    self.__cache[name] = self.__getmodule(name)
rpyc/core/netref.py:239: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
rpyc/core/netref.py:63: in syncreq
    return conn.sync_request(handler, proxy, *args)
rpyc/core/protocol.py:744: in sync_request
    return _async_res.value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f49323e02c0>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: No module named 'test_attributes'
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 369, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 863, in _handle_call
E               return obj(*args, **dict(kwargs))
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/service.py", line 162, in getmodule
E               return importlib.import_module(name)
E             File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
E               return _bootstrap._gcd_import(name[level:], package, level)
E             File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
E             File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
E             File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
E           ModuleNotFoundError: No module named 'test_attributes'

rpyc/core/async_.py:111: ModuleNotFoundError
___________________________ ClassicMode.test_modules ___________________________

self = <tests.test_classic.ClassicMode testMethod=test_modules>

    def test_modules(self):
>       self.assertIn('test_magic', self.conn.modules)
E       AssertionError: 'test_magic' not found in <rpyc.core.service.ModuleNamespace object at 0x7f493193ff40>

tests/test_classic.py:55: AssertionError
______________________________ Test_GDB.test_gdb _______________________________

self = <tests.test_gdb.Test_GDB testMethod=test_gdb>

    def test_gdb(self):
        print(0)
        parent_gdb_conn = rpyc.connect(host='localhost', port=18878)
        print(1)
        gdb = parent_gdb_conn.root.get_gdb()
        print(2)
>       gdb.execute('file {}'.format(self.a_out))

tests/test_gdb.py:63:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rpyc/core/netref.py:239: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
rpyc/core/netref.py:63: in syncreq
    return conn.sync_request(handler, proxy, *args)
rpyc/core/protocol.py:744: in sync_request
    return _async_res.value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f493195b010>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: connection closed by peer
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 369, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 863, in _handle_call
E               return obj(*args, **dict(kwargs))
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/netref.py", line 239, in __call__
E               return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/netref.py", line 63, in syncreq
E               return conn.sync_request(handler, proxy, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 744, in sync_request
E               return _async_res.value
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/async_.py", line 109, in value
E               self.wait()
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/async_.py", line 51, in wait
E               self._conn.serve(self._ttl, waiting=self._waiting)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 464, in serve
E               data = self._channel.poll(timeout) and self._channel.recv()
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/channel.py", line 55, in recv
E               header = self.stream.read(self.FRAME_HEADER.size)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/stream.py", line 280, in read
E               raise EOFError("connection closed by peer")
E           EOFError: connection closed by peer

rpyc/core/async_.py:111: EOFError
----------------------------- Captured stdout call -----------------------------
0
1
38227
2
_____________________ TestContextManagers.test_hash_class ______________________

self = <rpyc.core.service.ModuleNamespace object at 0x7f49323826c0>
name = 'test_magic'

    def __getattr__(self, name):
        """Provides dot notation access to modules"""
        try:
>           return self[name]

rpyc/core/service.py:138:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rpyc/core/service.py:132: in __getitem__
    self.__cache[name] = self.__getmodule(name)
rpyc/core/netref.py:239: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
rpyc/core/netref.py:63: in syncreq
    return conn.sync_request(handler, proxy, *args)
rpyc/core/protocol.py:744: in sync_request
    return _async_res.value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f49319c4a90>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: No module named 'test_magic'
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 369, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 863, in _handle_call
E               return obj(*args, **dict(kwargs))
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/service.py", line 162, in getmodule
E               return importlib.import_module(name)
E             File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
E               return _bootstrap._gcd_import(name[level:], package, level)
E             File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
E             File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
E             File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
E           ModuleNotFoundError: No module named 'test_magic'

rpyc/core/async_.py:111: ModuleNotFoundError

During handling of the above exception, another exception occurred:

self = <tests.test_magic.TestContextManagers testMethod=test_hash_class>

    def test_hash_class(self):
        hesh = self.conn.builtins.hash
>       mod = self.conn.modules.test_magic

tests/test_magic.py:40:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <rpyc.core.service.ModuleNamespace object at 0x7f49323826c0>
name = 'test_magic'

    def __getattr__(self, name):
        """Provides dot notation access to modules"""
        try:
            return self[name]
        except ImportError:
>           raise AttributeError(name)
E           AttributeError: test_magic

rpyc/core/service.py:140: AttributeError
______________________ TestContextManagers.test_hash_obj _______________________

self = <rpyc.core.service.ModuleNamespace object at 0x7f4932369440>
name = 'test_magic'

    def __getattr__(self, name):
        """Provides dot notation access to modules"""
        try:
>           return self[name]

rpyc/core/service.py:138:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rpyc/core/service.py:132: in __getitem__
    self.__cache[name] = self.__getmodule(name)
rpyc/core/netref.py:239: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
rpyc/core/netref.py:63: in syncreq
    return conn.sync_request(handler, proxy, *args)
rpyc/core/protocol.py:744: in sync_request
    return _async_res.value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f49319b7920>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: No module named 'test_magic'
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 369, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 863, in _handle_call
E               return obj(*args, **dict(kwargs))
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/service.py", line 162, in getmodule
E               return importlib.import_module(name)
E             File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
E               return _bootstrap._gcd_import(name[level:], package, level)
E             File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
E             File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
E             File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
E           ModuleNotFoundError: No module named 'test_magic'

rpyc/core/async_.py:111: ModuleNotFoundError

During handling of the above exception, another exception occurred:

self = <tests.test_magic.TestContextManagers testMethod=test_hash_obj>

    def test_hash_obj(self):
        hesh = self.conn.builtins.hash
>       mod = self.conn.modules.test_magic

tests/test_magic.py:56:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <rpyc.core.service.ModuleNamespace object at 0x7f4932369440>
name = 'test_magic'

    def __getattr__(self, name):
        """Provides dot notation access to modules"""
        try:
            return self[name]
        except ImportError:
>           raise AttributeError(name)
E           AttributeError: test_magic

rpyc/core/service.py:140: AttributeError
_________ Test_Netref_Hierarchy.test_instancecheck_across_connections __________

self = <tests.test_netref_hierachy.Test_Netref_Hierarchy testMethod=test_instancecheck_across_connections>

    def test_instancecheck_across_connections(self):
        self.conn2 = rpyc.classic.connect('localhost', port=18878)
>       self.conn.execute('import test_magic')

tests/test_netref_hierachy.py:111:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rpyc/core/netref.py:239: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
rpyc/core/netref.py:63: in syncreq
    return conn.sync_request(handler, proxy, *args)
rpyc/core/protocol.py:744: in sync_request
    return _async_res.value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f49319b7fb0>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: No module named 'test_magic'
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 369, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/protocol.py", line 863, in _handle_call
E               return obj(*args, **dict(kwargs))
E             File "/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/core/service.py", line 152, in execute
E               execute(text, self.namespace)
E             File "<string>", line 1, in <module>
E           ModuleNotFoundError: No module named 'test_magic'

rpyc/core/async_.py:111: ModuleNotFoundError
=============================== warnings summary ===============================
tests/test_threaded_server.py::Test_ThreadPoolServer::test_connection
  /home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/rpyc/utils/server.py:349: DeprecationWarning: setName() is deprecated, set the name attribute instead
    self.polling_thread.setName('PollingThread')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
SKIPPED [1] tests/test_deploy.py:86: Paramiko is not available
SKIPPED [1] tests/test_gevent_server.py:27: Gevent is not available
SKIPPED [1] tests/test_gevent_server.py:33: Gevent is not available
SKIPPED [1] tests/test_gevent_server.py:49: Gevent is not available
SKIPPED [1] tests/test_ipv6.py:19: requires IPv6
SKIPPED [1] tests/test_remoting.py:34: TODO: upload a package and a module
SKIPPED [1] tests/test_remoting.py:38: Requires manual testing atm
SKIPPED [1] tests/test_remoting.py:43: Requires manual testing atm
SKIPPED [1] tests/test_urllib3.py:28: urllib3 not available
SKIPPED [1] tests/test_win32pipes.py:11: Requires windows
SKIPPED [1] tests/test_win32pipes.py:24: Requires windows
SKIPPED [1] tests/test_win32pipes.py:56: Requires windows
FAILED tests/test_attributes.py::TestAttributes::test_properties - _get_excep...
FAILED tests/test_classic.py::ClassicMode::test_modules - AssertionError: 'te...
FAILED tests/test_gdb.py::Test_GDB::test_gdb - _get_exception_class.<locals>....
FAILED tests/test_magic.py::TestContextManagers::test_hash_class - AttributeE...
FAILED tests/test_magic.py::TestContextManagers::test_hash_obj - AttributeErr...
FAILED tests/test_netref_hierachy.py::Test_Netref_Hierarchy::test_instancecheck_across_connections
======== 6 failed, 75 passed, 12 skipped, 1 warning in 71.63s (0:01:11) ========
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -----------
alabaster                     0.7.16
Babel                         2.15.0
build                         1.2.1
charset-normalizer            3.3.2
defusedxml                    0.7.1
docutils                      0.20.1
exceptiongroup                1.1.3
hatchling                     1.24.2
idna                          3.7
imagesize                     1.4.1
importlib_metadata            7.1.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.4
MarkupSafe                    2.1.5
numpy                         1.26.5
packaging                     24.0
pandas                        2.2.1
pathspec                      0.12.1
pluggy                        1.4.0
plumbum                       1.8.3
Pygments                      2.18.0
pyproject_hooks               1.0.0
pytest                        8.1.1
python-dateutil               2.9.0.post0
pytz                          2024.1
requests                      2.31.0
snowballstemmer               2.2.0
Sphinx                        7.3.7
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
tokenize_rt                   5.2.0
tomli                         2.0.1
trove-classifiers             2024.5.17
urllib3                       2.2.1
wheel                         0.43.0
zipp                          3.18.2
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by kloczek** [comment]
BTW: I have in my build procedure tests/test_affinity.py and tests/test_service_pickle.py in --ignore list because I cannot locate on pypi `cfg_tests`
```console
__________________________________________________________________________ ERROR collecting tests/test_affinity.py __________________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/tests/test_affinity.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_affinity.py:4: in <module>
    import support
E   ModuleNotFoundError: No module named 'support'
_______________________________________________________________________ ERROR collecting tests/test_service_pickle.py _______________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rpyc-6.0.0/tests/test_service_pickle.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_service_pickle.py:7: in <module>
    import cfg_tests
E   ModuleNotFoundError: No module named 'cfg_tests'
================================================================================== short test summary info ==================================================================================```
May I ask for some hint? 🤔

**Comment by kloczek** [comment]
https://github.com/tomerfiliba-org/rpyc/issues/544 still is opened.
Will continue in that ticket.
